import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Background from "../components/Background"
import Gratitude from "../components/Gratitude"
import Navbar from "../components/Navbar"
import NavMenu from "../components/NavMenu"
import Quote from "../components/Quote"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center">
        <NavMenu />
        <div className="flex flex-col items-center w-screen h-screen">
          <Background />
          <Quote />
          <Gratitude />
        </div>
      </div>
    </div>
  )
}

export default Home
