import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Background from "../components/Background"
import Gratitude from "../components/Gratitude"
import Login from "../components/Login"
import Navbar from "../components/Navbar"
import NavMenu from "../components/NavMenu"
import Quote from "../components/Quote"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100 w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        <h1 className="text-4xl font-bold py-20">Sign in to your account</h1>
      <Login />
      </div>
    </div>
  )
}

export default Home
